# Generated by Django 3.1 on 2020-08-13 10:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0001_initial'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('mobile_phone', models.PositiveIntegerField()),
                ('email_address', models.CharField(max_length=128)),
                ('other_customer_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPreferences',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('customer_preferences_details', models.TextField()),
                ('car_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_feature', to='car.carfeatures')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custormer', to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPayments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('customer_payment_date_due', models.DateField()),
                ('customer_payment_date_made', models.DateField()),
                ('actual_payment_amount', models.DecimalField(decimal_places=4, max_digits=5)),
                ('car_sold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_sold', to='car.carsold')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='customer.customer')),
                ('payment_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_status', to='payment.paymentstatus')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('address_line1', models.TextField()),
                ('address_line2', models.TextField()),
                ('address_line3', models.TextField()),
                ('address_line4', models.TextField()),
                ('town_city', models.TextField()),
                ('state_province', models.TextField()),
                ('country', models.TextField()),
                ('post_zip_code', models.IntegerField()),
                ('other_address_details', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_adress', to='customer.customer')),
            ],
        ),
    ]
