# Generated by Django 3.1 on 2020-08-13 10:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('payment_status_code', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('payment_status_description', models.TextField()),
            ],
        ),
    ]
