# Generated by Django 3.1 on 2020-08-13 10:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarFeatures',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('car_feature_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CarManufacturer',
            fields=[
                ('manufacturer_short_name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('manufacturer_full_name', models.TextField()),
                ('manufacturer_other_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('model_code', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('manufacturer_code', models.SmallIntegerField()),
                ('model_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='CarSale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('asking_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('current_km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_acquired', models.DateField()),
                ('other_car_details', models.TextField()),
                ('manufacturer_short_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CarManufacturer', to='car.carmanufacturer')),
                ('model_code', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='car.carmodel')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('vehicle_category_name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('vehicle_category_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InsurancePolicies',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('policy_start_date', models.DateField()),
                ('policy_end_date', models.DateField()),
                ('insurance_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_companies', to='payment.insurancecompany')),
            ],
        ),
        migrations.CreateModel(
            name='FeaturesForSaleCars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_features', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='car.carfeatures')),
                ('car_for_sale', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='car.carsale')),
            ],
        ),
        migrations.CreateModel(
            name='CarSold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('agreed_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_sold', models.DateField()),
                ('car_for_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carsale', to='car.carsale')),
                ('finance_companies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_company', to='payment.financecompany')),
            ],
        ),
        migrations.AddField(
            model_name='carsale',
            name='vehicle_category',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='car.vehiclecategory'),
        ),
        migrations.CreateModel(
            name='CarLoans',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('payment_start_date', models.DateField()),
                ('payment_end_date', models.DateField()),
                ('monthly_payments', models.DecimalField(decimal_places=2, max_digits=5)),
                ('car_sold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carsolds', to='car.carsold')),
                ('finance_companies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_companies', to='payment.financecompany')),
            ],
        ),
    ]
